# Generated by Django 4.0 on 2022-03-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0003_rename_create_team_team_count_create_team_create_team_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_leave_status',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_topic_status',
        ),
        migrations.RemoveField(
            model_name='trainer_task',
            name='trainer_task_task_status',
        ),
    ]
