# Generated by Django 4.0 on 2022-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0004_remove_leave_leave_leave_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acntspayslip',
            name='acntspayslip_esitype',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='acntspayslip',
            name='acntspayslip_pftype',
            field=models.CharField(default='', max_length=255),
        ),
    ]
